create extension if not exists pgcrypto;

create table if not exists public.characters (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name_vi text not null,
  name_en text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.participants (
  id uuid primary key default gen_random_uuid(),
  visitor_id text not null unique,
  name text not null,
  class_name text,
  school_name text,
  first_seen timestamptz not null default now(),
  last_seen timestamptz not null default now()
);

create table if not exists public.sessions (
  id uuid primary key default gen_random_uuid(),
  session_id text not null unique,
  participant_id uuid not null references public.participants(id) on delete cascade,
  character_id uuid not null references public.characters(id) on delete cascade,
  language text not null default 'vi',
  started_at timestamptz not null default now(),
  last_seen timestamptz not null default now(),
  ended_at timestamptz,
  duration_seconds integer not null default 0,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  external_event_id text not null unique,
  session_id uuid not null references public.sessions(id) on delete cascade,
  participant_id uuid not null references public.participants(id) on delete cascade,
  character_id uuid not null references public.characters(id) on delete cascade,
  event_type text not null,
  feature text,
  content text,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists idx_events_occurred_at on public.events(occurred_at desc);
create index if not exists idx_events_character_id on public.events(character_id);
create index if not exists idx_events_participant_id on public.events(participant_id);
create index if not exists idx_events_event_type on public.events(event_type);
create index if not exists idx_sessions_character_id on public.sessions(character_id);
create index if not exists idx_sessions_participant_id on public.sessions(participant_id);
create index if not exists idx_sessions_started_at on public.sessions(started_at desc);

alter table public.characters enable row level security;
alter table public.participants enable row level security;
alter table public.sessions enable row level security;
alter table public.events enable row level security;

-- Không tạo policy cho anon/authenticated: dữ liệu chỉ đi qua backend dùng server secret/service role.
revoke all on public.characters from anon, authenticated;
revoke all on public.participants from anon, authenticated;
revoke all on public.sessions from anon, authenticated;
revoke all on public.events from anon, authenticated;

create or replace function public.analytics_snapshot(
  p_from timestamptz default null,
  p_to timestamptz default null,
  p_character_slug text default null,
  p_class_name text default null,
  p_school_name text default null
) returns jsonb
language sql
security definer
set search_path = public
as $$
with filtered_sessions as (
  select s.*, p.name as participant_name, p.class_name, p.school_name,
         c.slug as character_slug, c.name_vi as character_name
  from sessions s
  join participants p on p.id = s.participant_id
  join characters c on c.id = s.character_id
  where (p_from is null or s.started_at >= p_from)
    and (p_to is null or s.started_at <= p_to)
    and (p_character_slug is null or c.slug = p_character_slug)
    and (p_class_name is null or coalesce(p.class_name,'') ilike '%' || p_class_name || '%')
    and (p_school_name is null or coalesce(p.school_name,'') ilike '%' || p_school_name || '%')
),
filtered_events as (
  select e.*, fs.character_slug, fs.character_name, fs.participant_name, fs.class_name, fs.school_name
  from events e
  join filtered_sessions fs on fs.id = e.session_id
  where (p_from is null or e.occurred_at >= p_from)
    and (p_to is null or e.occurred_at <= p_to)
),
session_character_stats as (
  select character_id,
         count(distinct participant_id)::int as participants,
         count(*)::int as sessions,
         coalesce(sum(duration_seconds),0)::int as duration_seconds
  from filtered_sessions
  group by character_id
),
event_character_stats as (
  select character_id,
         count(*)::int as interactions,
         greatest(count(*) filter (where event_type = 'favorite_add') - count(*) filter (where event_type = 'favorite_remove'), 0)::int as favorites
  from filtered_events
  group by character_id
),
character_stats as (
  select c.slug,
         c.name_vi as name,
         coalesce(sc.participants,0)::int as participants,
         coalesce(sc.sessions,0)::int as sessions,
         coalesce(ec.interactions,0)::int as interactions,
         coalesce(ec.favorites,0)::int as favorites,
         coalesce(sc.duration_seconds,0)::int as duration_seconds
  from characters c
  left join session_character_stats sc on sc.character_id = c.id
  left join event_character_stats ec on ec.character_id = c.id
  where c.active = true
    and (p_character_slug is null or c.slug = p_character_slug)
),
participant_session_stats as (
  select participant_id,
         max(participant_name) as name,
         max(class_name) as class_name,
         max(school_name) as school_name,
         count(*)::int as sessions,
         coalesce(sum(duration_seconds),0)::int as duration_seconds,
         max(last_seen) as last_seen
  from filtered_sessions
  group by participant_id
),
participant_event_stats as (
  select participant_id, count(*)::int as interactions
  from filtered_events
  group by participant_id
),
participant_stats as (
  select ps.participant_id,
         ps.name,
         ps.class_name,
         ps.school_name,
         ps.sessions,
         coalesce(pe.interactions,0)::int as interactions,
         ps.duration_seconds,
         ps.last_seen
  from participant_session_stats ps
  left join participant_event_stats pe on pe.participant_id = ps.participant_id
  order by interactions desc, sessions desc
  limit 100
),
feature_stats as (
  select coalesce(nullif(feature,''), event_type) as feature,
         count(*)::int as count
  from filtered_events
  group by 1
  order by count desc
),
daily_stats as (
  select to_char(date_trunc('day', occurred_at at time zone 'Asia/Ho_Chi_Minh'), 'YYYY-MM-DD') as day,
         count(*)::int as interactions,
         count(distinct participant_id)::int as participants,
         count(distinct session_id)::int as sessions
  from filtered_events
  group by 1
  order by 1
),
recent_events as (
  select jsonb_build_object(
    'eventType', fe.event_type,
    'feature', fe.feature,
    'content', left(coalesce(fe.content,''), 250),
    'occurredAt', fe.occurred_at,
    'participant', fe.participant_name,
    'className', fe.class_name,
    'schoolName', fe.school_name,
    'characterSlug', fe.character_slug,
    'character', fe.character_name
  ) as item
  from filtered_events fe
  order by fe.occurred_at desc
  limit 50
)
select jsonb_build_object(
  'totals', jsonb_build_object(
    'characters', (select count(*)::int from characters where active = true),
    'participants', (select count(distinct participant_id)::int from filtered_sessions),
    'sessions', (select count(distinct id)::int from filtered_sessions),
    'interactions', (select count(*)::int from filtered_events),
    'favorites', (select greatest(count(*) filter (where event_type = 'favorite_add') - count(*) filter (where event_type = 'favorite_remove'), 0)::int from filtered_events),
    'durationSeconds', (select coalesce(sum(duration_seconds),0)::int from filtered_sessions)
  ),
  'characters', coalesce((select jsonb_agg(to_jsonb(character_stats) order by interactions desc, sessions desc) from character_stats), '[]'::jsonb),
  'participants', coalesce((select jsonb_agg(to_jsonb(participant_stats) order by interactions desc, sessions desc) from participant_stats), '[]'::jsonb),
  'features', coalesce((select jsonb_agg(to_jsonb(feature_stats) order by count desc) from feature_stats), '[]'::jsonb),
  'daily', coalesce((select jsonb_agg(to_jsonb(daily_stats) order by day) from daily_stats), '[]'::jsonb),
  'recentEvents', coalesce((select jsonb_agg(item) from recent_events), '[]'::jsonb)
);
$$;

revoke all on function public.analytics_snapshot(timestamptz,timestamptz,text,text,text) from public, anon, authenticated;
grant execute on function public.analytics_snapshot(timestamptz,timestamptz,text,text,text) to service_role;
