-- HISTORY ANALYTICS MANAGER v1.1.0
-- Nâng cấp an toàn từ v1.0.x: chỉ thêm bảng quản lý, không xóa dữ liệu thống kê.
create extension if not exists pgcrypto;

create table if not exists public.admins (
  id uuid primary key default gen_random_uuid(),
  username text not null,
  username_key text not null unique,
  password_hash text not null,
  role text not null default 'manager' check (role in ('master','manager')),
  active boolean not null default true,
  session_version integer not null default 1,
  last_login timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.admins(id) on delete set null,
  target_id uuid references public.admins(id) on delete set null,
  action text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_admins_role_active on public.admins(role, active);
create index if not exists idx_admin_audit_created_at on public.admin_audit_logs(created_at desc);

alter table public.admins enable row level security;
alter table public.admin_audit_logs enable row level security;
revoke all on public.admins from anon, authenticated;
revoke all on public.admin_audit_logs from anon, authenticated;
